#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "sublink-worker-SUBLINK_KV", id = "4423ff9f62544f5abb305d29bda1ae3a" }
]

[assets]
directory = "./public"
